// Создаёт Data-Table `project_architecture` в БД n8n (Postgres) — хранилище сгенерированной
// архитектуры проекта (см. wf_api_architecture.json / build_wf_api_architecture.mjs).
//
// Зачем напрямую в Postgres, а не через UI: n8n Data-Table = строка в реестре `data_table`
// + по строке на колонку в `data_table_column` + физическая таблица `data_table_user_<id>`.
// bootstrap.sh таблицы НЕ создаёт декларативно (они приходят из restore или создаются вручную).
// Скрипт воспроизводит формат существующих таблиц (образец — `projects`) и идемпотентен:
// если таблица уже есть — выходит без изменений.
//
// ВАЖНО: после создания n8n нужно ПЕРЕЗАПУСТИТЬ (docker restart docs-n8n) — модуль Data-Tables
// кеширует реестр, иначе dataTable-нода не увидит новую таблицу. Перезапуск убивает идущую
// обработку — запускайте на простаивающем стенде (скрипт сам НЕ рестартит, лишь печатает команду).
//
// Запуск:  node create_project_architecture_table.mjs
// Контейнер/БД переопределяются env: PG_CONTAINER (docs-postgres), PG_USER (n8n), PG_DB (n8n).

import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';

const PG_CONTAINER = process.env.PG_CONTAINER || 'docs-postgres';
const PG_USER = process.env.PG_USER || 'n8n';
const PG_DB = process.env.PG_DB || 'n8n';
const TABLE = 'project_architecture';

// Колонки логической Data-Table: [имя, тип n8n, физ.тип Postgres]. Порядок = index 0..N.
// id/createdAt/updatedAt — системные у n8n (зарезервированы), их добавляем как у `projects`.
const COLUMNS = [
  ['project_id', 'string', 'text'],
  ['status', 'string', 'text'],
  ['generated_at', 'date', 'timestamp(3) with time zone'],
  ['provider', 'string', 'text'],
  ['model', 'string', 'text'],
  ['sources_count', 'number', 'double precision'],
  ['summary_md', 'string', 'text'],
  ['c4_context', 'string', 'text'],
  ['c4_container', 'string', 'text'],
  ['raw_json', 'string', 'text'],
];

const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
const nano = (n = 16) => {
  const b = randomBytes(n);
  let s = '';
  for (let i = 0; i < n; i++) s += ALPHABET[b[i] % ALPHABET.length];
  return s;
};

const psql = (sql, args = []) =>
  execFileSync(
    'docker',
    ['exec', '-i', PG_CONTAINER, 'psql', '-U', PG_USER, '-d', PG_DB, '-v', 'ON_ERROR_STOP=1', ...args],
    { input: sql, encoding: 'utf8' },
  );

// 1) Идемпотентность: уже есть?
const existing = psql(
  `SELECT id FROM data_table WHERE name='${TABLE}';`,
  ['-t', '-A'],
).trim();
if (existing) {
  console.log(`[create-table] '${TABLE}' уже существует (id=${existing}) — пропускаю.`);
  process.exit(0);
}

const tableId = nano();
const physical = `data_table_user_${tableId}`;

// Физические колонки + системные (как у projects: id identity PK, createdAt/updatedAt).
const physCols = COLUMNS.map(([name, , pg]) => `  "${name}" ${pg}`).join(',\n');

// Сборка одной транзакции: реестр + колонки + физическая таблица.
// projectId берём из любой существующей таблицы (единый n8n-проект).
const colInserts = COLUMNS.map(
  ([name, type], i) =>
    `INSERT INTO data_table_column (id, name, type, "index", "dataTableId", "createdAt", "updatedAt") ` +
    `VALUES ('${nano()}', '${name}', '${type}', ${i}, '${tableId}', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));`,
).join('\n');

const sql = `
BEGIN;

INSERT INTO data_table (id, name, "projectId", "createdAt", "updatedAt")
VALUES ('${tableId}', '${TABLE}', (SELECT "projectId" FROM data_table LIMIT 1), CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

${colInserts}

CREATE TABLE "${physical}" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
${physCols},
  "createdAt" timestamp(3) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updatedAt" timestamp(3) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT "PK_${physical}" PRIMARY KEY ("id")
);

COMMIT;
`;

console.log(`[create-table] создаю '${TABLE}' (id=${tableId}, физ. ${physical})…`);
try {
  const out = psql(sql);
  process.stdout.write(out);
} catch (e) {
  console.error('[create-table] ОШИБКА применения SQL:', e.stderr || e.message);
  process.exit(1);
}

// Проверка.
const check = psql(
  `SELECT c.name, c.type FROM data_table_column c JOIN data_table t ON t.id=c."dataTableId" WHERE t.name='${TABLE}' ORDER BY c."index";`,
  ['-t', '-A', '-F', '|'],
).trim();
console.log(`[create-table] готово. Колонки:\n${check}`);
console.log(
  `\n[create-table] ⚠ ПЕРЕЗАПУСТИТЕ n8n, чтобы он увидел таблицу:\n    docker restart ${process.env.N8N_CONTAINER || 'docs-n8n'}`,
);
